### PR TITLE
Add new grammar to retrieve variation selectors presence in the next grammar token

### PR DESCRIPTION
**Pull request by tursunova**
Add new grammar for retrieving extra information about variation selectors presence in the next grammar token. The added grammar is working same as existent `scan_emoji_presentation`, except that it also returns whether the next grammar token has variation selector 15 (U+FE0E) or variation selector 16 (U+FE0F).

This changes are required for font-variant-emoji CSS property support in Blink, see https://crrev.com/c/5776108.

### CODE REVIEW

**Review by drott — APPROVED** [review]
LGTM, thanks.

**Comment by behdad** [comment]
Thanks Munira.

The duplication bothers me. Can we just have one?

**Comment by drott** [comment]
> The duplication bothers me. Can we just have one?

Would you be okay if we just replace the main one with one that issues VS information? My thinking was that might not be needed for all clients, but I am okay with merging them.

**Comment by behdad** [comment]
> > The duplication bothers me. Can we just have one?
> 
> Would you be okay if we just replace the main one with one that issues VS information? My thinking was that might not be needed for all clients, but I am okay with merging them.

That's what I was suggesting. We can measure the binary size difference of the two. If the difference is negligible, I'm all for just having that one.

**Comment by behdad** [comment]
What ragel version does this work with? Not 7:
```

behdad:emoji-segmenter 0 (master)$ make
ragel emoji_presentation_scanner_vs.rl
emoji_presentation_scanner_vs.rl:19:9: warning: unrecognized write option "noentry"
behdad:emoji-segmenter 0 (master*)$ ragel --version
Ragel State Machine Compiler version 7.0.4 February 2021
```

Probably the older 6.x series?

**Comment by drott** [comment]
> Probably the older 6.x series?

Works for me with 
```
$ ragel --version
Ragel State Machine Compiler version 6.10 March 2017
```
Do you recommend regenerating with the newer one? 

We also did not find any benefits (but more compile warnings) with -F1, so we were thinking to remove that from the Makefile.

**Comment by behdad** [comment]
I'll try to add a harness and build binaries of these so we can measure.

I suggest working with ragel 6.9 or 7.0. What does `noentry` does anyway? I don't see it in the 6.9 manual either.

Re `F1`, since it just duplicates the actions, it's conceivable that it has no effect on a scanner like ours.  But then at least we should use `F0` instead, since the default is `T0` which uses bsearch, which `F0` avoids.

**Comment by drott** [comment]
> I'll try to add a harness and build binaries of these so we can measure.

Thanks, a local quick and dirty attempt at binary comparison did not lead to good results. 

> Re F1, since it just duplicates the actions, it's conceivable that it has no effect on a scanner like ours. But then at least we should use F0 instead, since the default is T0 which uses bsearch, which F0 avoids.

Ack, let's try `-F0`. 



> I suggest working with ragel 6.9 or 7.0.

Ok. Debian has 6.10, that should work then? We'll regenerate with that.

https://www.colm.net/news/2015/09/26/first-dev-version-of-ragel-7-released.html - is what I looked at. Rust output is an interesting addition, even though the way we use it in Blink does not really allow switching to Rust.

**Comment by tursunova** [comment]
Thank you Dominik and Behdad! 

I have tried compiling Chromium with -F0 mode generated file, but it still is not compiling cleanly in Chromium. 

Also I'm using Ragel version 6.10 but I didn't have any compile warning because of `"noentry"`.

Here is a pr for merging files: https://github.com/google/emoji-segmenter/pull/6

**Comment by behdad** [comment]
Thanks. I also made a PR just showing size comparisons and generally compile the output:
https://github.com/google/emoji-segmenter/pull/7

**Comment by behdad** [comment]
I can merge mine after yours. I have to figure out what "noentry" means and if it's safe to remove it.

Can you paste the Chromium error please?

**Comment by tursunova** [comment]
Sure, I pasted only errors here:
```
emoji_presentation_scanner.c:130:42: error: invalid operands to binary expression ('const unsigned char' and 'EmojiSegmentationCategory')
  130 |     _trans = _inds[_slen > 0 && _keys[0] <= (*p) && (*p) <= _keys[1]
      |                                 ~~~~~~~~ ^  ~~~~
emoji_presentation_scanner.c:130:58: error: invalid operands to binary expression ('EmojiSegmentationCategory' and 'const unsigned char')
  130 |     _trans = _inds[_slen > 0 && _keys[0] <= (*p) && (*p) <= _keys[1]
      |                                                     ~~~~ ^  ~~~~~~~~
emoji_presentation_scanner.c:131:31: error: invalid operands to binary expression ('EmojiSegmentationCategory' and 'const unsigned char')
  131 |                        ? (*p) - _keys[0]
```

here is the full output: https://pastebin.com/dY9MULju

**Comment by behdad** [comment]
> Sure, I pasted only errors here:

Can we implement those two operators so it works?

**Comment by drott** [comment]
> Can we implement those two operators so it works?

Done in [5837543](https://chromium-review.googlesource.com/c/chromium/src/+/5837543)  - I had lost sight of the fact that we had a couple of other ones implemented already, thanks for the reminder that this is a good way to address this without inserting manual casts to the code.

**Comment by drott** [comment]
@tursunova when https://chromium-review.googlesource.com/c/chromium/src/+/5837543 goes green on the bots or lands, can you update this pull request to put back the `-F1` mode and regenerate the C code files, squash commits and update the commit message to contain what version of Ragel the files were generated with, then we can merge this. 

@behdad Thank you for the binary size comparison. I had one comment on the CL, perhaps you can indeed then land it after Munira's change, so we have the extra Makefile steps and a means of measuring output size.

**Comment by tursunova** [comment]
Thanks, done, https://github.com/google/emoji-segmenter/pull/6
